"""
Forge: App Builder & Zero-Vision Native Control Engine
======================================================
Builds and manages custom local applications (e.g. retail/inventory tools, CRM,
calculators, trackers). Crucially, Forge generates internal control hooks and schemas
so that Maestro and Autopilot can natively manipulate these built apps without needing
slow vision or image OCR models.
"""

import json
import os
import time
from typing import Any, Dict, List, Optional


FORGE_DIR = os.path.expanduser("~/.momento/forge")
APPS_REGISTRY_FILE = os.path.join(FORGE_DIR, "forge_apps.json")


def ensure_forge_dir() -> None:
    os.makedirs(FORGE_DIR, exist_ok=True)
    if not os.path.exists(APPS_REGISTRY_FILE):
        with open(APPS_REGISTRY_FILE, "w", encoding="utf-8") as f:
            json.dump([], f, indent=2)


class ForgeEngine:
    """Creates local software and exposes zero-vision programmatic control hooks."""

    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir or FORGE_DIR
        self.registry_file = os.path.join(self.output_dir, "forge_apps.json")
        os.makedirs(self.output_dir, exist_ok=True)
        if not os.path.exists(self.registry_file):
            with open(self.registry_file, "w", encoding="utf-8") as f:
                json.dump([], f, indent=2)

    def list_apps(self) -> List[Dict[str, Any]]:
        """List all generated custom Forge applications."""
        os.makedirs(self.output_dir, exist_ok=True)
        if os.path.exists(self.registry_file):
            try:
                with open(self.registry_file, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                return []
        return []

    def get_app(self, app_id: str) -> Optional[Dict[str, Any]]:
        """Retrieve a specific Forge app by ID."""
        for app in self.list_apps():
            if app.get("id") == app_id:
                return app
        return None

    def build_app(
        self,
        name: str,
        category: str = "business",
        description: str = "",
        fields: Optional[List[Dict[str, Any]]] = None,
        actions: Optional[List[str]] = None,
        initial_data: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, Any]:
        """
        Generate and register a new local software application with internal control schema.
        Crucially exposes programmatic zero-vision control hooks.
        """
        clean_name = name.strip()
        if not clean_name:
            return {"success": False, "error": "App name cannot be empty"}

        app_id = f"forge_{clean_name.lower().replace(' ', '_').replace('-', '_')}"
        app_file = os.path.join(self.output_dir, f"{app_id}.json")

        app_fields = fields or [
            {"id": "sku", "name": "Item SKU", "type": "string", "required": True},
            {"id": "title", "name": "Item Name", "type": "string", "required": True},
            {"id": "quantity", "name": "Stock Quantity", "type": "integer", "required": True},
            {"id": "price", "name": "Unit Price ($)", "type": "number", "required": True}
        ]

        app_actions = actions or ["add_record", "update_record", "delete_record", "export_csv", "clear_all"]

        app_data = list(initial_data) if initial_data is not None else [
            {"sku": "SKU-1001", "title": "Standard Widget", "quantity": 45, "price": 12.99},
            {"sku": "SKU-1002", "title": "Premium Component", "quantity": 18, "price": 49.50}
        ]

        # Zero-vision internal control schema
        control_schema = {
            "api_endpoint": f"/api/client/forge/apps/{app_id}/execute",
            "supported_hooks": {
                "create": {"action": "add_record", "params": [f["id"] for f in app_fields]},
                "read": {"action": "query_records", "params": ["filter", "field"]},
                "update": {"action": "update_record", "params": ["id_field", "value", "updates"]},
                "delete": {"action": "delete_record", "params": ["id_field", "value"]}
            },
            "interactive_fields": app_fields,
            "zero_vision_enabled": True
        }

        record = {
            "id": app_id,
            "name": clean_name,
            "category": category,
            "description": description or f"Zero-Vision native {category} tool generated by Forge.",
            "fields": app_fields,
            "actions": app_actions,
            "data": app_data,
            "control_schema": control_schema,
            "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "last_updated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "zero_vision_control": True
        }

        # Write app state
        with open(app_file, "w", encoding="utf-8") as f:
            json.dump(record, f, indent=2)

        # Update registry
        apps = self.list_apps()
        apps = [a for a in apps if a.get("id") != app_id]
        apps.insert(0, record)
        with open(self.registry_file, "w", encoding="utf-8") as f:
            json.dump(apps, f, indent=2)

        return {
            "success": True,
            "app": record,
            "message": f"Forge: Successfully built '{clean_name}' with native zero-vision control schema."
        }

    def execute_app_hook(
        self,
        app_id: str,
        action: str,
        payload: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Execute native zero-vision control hook on Forge app without visual models.
        Maestro or Autopilot calls this directly.
        """
        app = self.get_app(app_id)
        if not app:
            return {"success": False, "error": f"Forge app '{app_id}' not found"}

        params = payload or {}
        data = app.get("data", [])
        log_line = ""

        if action in ("add_record", "create"):
            data.append(params)
            log_line = f"Inserted record into {app['name']}: {params}"
        elif action in ("update_record", "update"):
            key = params.get("id_field", "sku")
            val = params.get("value")
            updates = params.get("updates", {})
            matched = False
            for item in data:
                if str(item.get(key)) == str(val):
                    item.update(updates)
                    matched = True
                    break
            log_line = f"Updated record {key}={val} in {app['name']}: {updates}" if matched else f"Record {key}={val} not found."
        elif action in ("delete_record", "delete"):
            key = params.get("id_field", "sku")
            val = params.get("value")
            data = [d for d in data if str(d.get(key)) != str(val)]
            log_line = f"Deleted record {key}={val} from {app['name']}."
        elif action == "clear_all":
            data = []
            log_line = f"Cleared all records from {app['name']}."
        else:
            log_line = f"Executed action '{action}' on {app['name']}."

        app["data"] = data
        app["last_updated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        # Persist update
        app_file = os.path.join(self.output_dir, f"{app_id}.json")
        try:
            with open(app_file, "w", encoding="utf-8") as f:
                json.dump(app, f, indent=2)
        except Exception:
            pass

        apps = self.list_apps()
        for i, a in enumerate(apps):
            if a.get("id") == app_id:
                apps[i] = app
                break
        try:
            with open(self.registry_file, "w", encoding="utf-8") as f:
                json.dump(apps, f, indent=2)
        except Exception:
            pass

        return {
            "success": True,
            "app_id": app_id,
            "action": action,
            "total_records": len(data),
            "log": log_line,
            "zero_vision_used": True
        }


# Global singleton
global_forge_engine = ForgeEngine()
