"""
Momento File Exporter Service.
Compiles transformed AI output back into native downloadable file formats:
- Microsoft Word (.docx)
- Microsoft Excel (.xlsx)
- Comma-Separated Values (.csv)
- Markdown (.md) & Plain Text (.txt)
"""

import os
import re
import csv
import io
import uuid
import time
from typing import Dict, Any, List, Optional
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


DOWNLOADS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "downloads"))


def ensure_downloads_dir() -> str:
    """Ensure downloads directory exists and return absolute path."""
    os.makedirs(DOWNLOADS_DIR, exist_ok=True)
    return DOWNLOADS_DIR


def format_bytes_human(num_bytes: int) -> str:
    """Format bytes to human-readable string."""
    if num_bytes == 0:
        return "0 B"
    for unit in ["B", "KB", "MB", "GB"]:
        if abs(num_bytes) < 1024.0:
            return f"{num_bytes:.1f} {unit}"
        num_bytes /= 1024.0
    return f"{num_bytes:.1f} TB"


def parse_markdown_tables(text: str) -> List[List[List[str]]]:
    """Extract all markdown tables as list of 2D row/cell matrices."""
    tables = []
    current_table = []
    
    for line in text.split("\n"):
        line_str = line.strip()
        if line_str.startswith("|") and line_str.endswith("|"):
            # Check if this is a separator line like |---|---|
            stripped_content = line_str.replace("|", "").replace("-", "").replace(":", "").strip()
            if not stripped_content:
                continue
            cells = [c.strip() for c in line_str.split("|")[1:-1]]
            current_table.append(cells)
        else:
            if current_table:
                tables.append(current_table)
                current_table = []
                
    if current_table:
        tables.append(current_table)
        
    return tables


def parse_text_to_matrix(text: str) -> List[List[str]]:
    """Convert text, markdown table, or CSV lines into a 2D matrix for spreadsheets."""
    # First check for markdown tables
    tables = parse_markdown_tables(text)
    if tables:
        # Return the largest table found
        return max(tables, key=len)

    # Check for CSV formatted rows
    lines = [line.strip() for line in text.strip().split("\n") if line.strip()]
    csv_rows = []
    for line in lines:
        if "," in line:
            reader = csv.reader([line])
            for row in reader:
                csv_rows.append(row)
        elif "\t" in line:
            csv_rows.append(line.split("\t"))
        else:
            csv_rows.append([line])
            
    if csv_rows:
        return csv_rows

    return [["Momento Output", text[:500]]]


def compile_docx(content: str, output_path: str, title: Optional[str] = None) -> None:
    """Compile content into a beautifully formatted Word document (.docx)."""
    doc = Document()

    # Document Header / Title
    doc_title = title or "Momento Generated Document"
    title_para = doc.add_paragraph()
    title_run = title_para.add_run(doc_title)
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(30, 58, 138)  # Deep Indigo
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT

    # Add subtitle metadata
    meta_para = doc.add_paragraph()
    meta_run = meta_para.add_run(f"Generated by Momento AI • {time.strftime('%B %d, %Y')}")
    meta_run.font.size = Pt(9.5)
    meta_run.font.italic = True
    meta_run.font.color.rgb = RGBColor(100, 116, 139)

    doc.add_paragraph()  # Space

    lines = content.split("\n")
    in_table = False
    table_lines = []

    def flush_table():
        nonlocal table_lines
        if not table_lines:
            return
        matrix = []
        for tl in table_lines:
            cells = [c.strip() for c in tl.split("|")[1:-1]]
            matrix.append(cells)
        if matrix:
            max_cols = max(len(r) for r in matrix)
            tbl = doc.add_table(rows=len(matrix), cols=max_cols)
            tbl.alignment = WD_TABLE_ALIGNMENT.CENTER
            tbl.style = "Light Shading Accent 1" if "Light Shading Accent 1" in [s.name for s in doc.styles] else "Table Grid"

            for r_idx, row in enumerate(matrix):
                for c_idx in range(max_cols):
                    cell_val = row[c_idx] if c_idx < len(row) else ""
                    cell = tbl.cell(r_idx, c_idx)
                    cell.text = cell_val
                    if r_idx == 0:
                        for paragraph in cell.paragraphs:
                            for run in paragraph.runs:
                                run.font.bold = True
            doc.add_paragraph()
        table_lines = []

    for line in lines:
        stripped = line.strip()

        # Handle Markdown Tables
        if stripped.startswith("|") and stripped.endswith("|"):
            # Check if separator
            stripped_mid = stripped.replace("|", "").replace("-", "").replace(":", "").strip()
            if not stripped_mid:
                continue
            in_table = True
            table_lines.append(stripped)
            continue
        elif in_table:
            in_table = False
            flush_table()

        if not stripped:
            continue

        # Headings
        if stripped.startswith("### "):
            heading = doc.add_heading(stripped[4:], level=3)
            heading.paragraph_format.space_before = Pt(8)
            heading.paragraph_format.space_after = Pt(4)
        elif stripped.startswith("## "):
            heading = doc.add_heading(stripped[3:], level=2)
            heading.paragraph_format.space_before = Pt(12)
            heading.paragraph_format.space_after = Pt(4)
        elif stripped.startswith("# "):
            heading = doc.add_heading(stripped[2:], level=1)
            heading.paragraph_format.space_before = Pt(16)
            heading.paragraph_format.space_after = Pt(6)
        # Bullet list items
        elif stripped.startswith("- ") or stripped.startswith("* "):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(stripped[2:])
        # Numbered list items
        elif re.match(r"^\d+\.\s", stripped):
            p = doc.add_paragraph(style="List Number")
            text_part = re.sub(r"^\d+\.\s", "", stripped)
            p.add_run(text_part)
        else:
            p = doc.add_paragraph()
            # Clean bold/italic markdown marks for clean reading
            cleaned = stripped.replace("**", "").replace("__", "")
            p.add_run(cleaned)

    if in_table:
        flush_table()

    doc.save(output_path)


def compile_xlsx(content: str, output_path: str, sheet_title: str = "Momento Data") -> None:
    """Compile content into a styled Excel spreadsheet (.xlsx)."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_title[:31]

    matrix = parse_text_to_matrix(content)
    if not matrix:
        matrix = [["Output"], [content]]

    # Styles
    header_fill = PatternFill(start_color="1E3A8A", end_color="1E3A8A", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    data_font = Font(name="Calibri", size=10)
    thin_border = Border(
        left=Side(style="thin", color="E2E8F0"),
        right=Side(style="thin", color="E2E8F0"),
        top=Side(style="thin", color="E2E8F0"),
        bottom=Side(style="thin", color="E2E8F0"),
    )
    align_center = Alignment(horizontal="left", vertical="center", wrap_text=True)

    for row_idx, row in enumerate(matrix, start=1):
        for col_idx, cell_value in enumerate(row, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=cell_value)
            cell.border = thin_border
            cell.alignment = align_center

            if row_idx == 1:
                cell.fill = header_fill
                cell.font = header_font
            else:
                cell.font = data_font
                if row_idx % 2 == 0:
                    cell.fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")

    # Auto-adjust column widths
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            val_str = str(cell.value or "")
            if len(val_str) > max_len:
                max_len = len(val_str)
        adjusted_width = min(max(max_len + 3, 12), 50)
        ws.column_dimensions[col_letter].width = adjusted_width

    wb.save(output_path)


def compile_csv(content: str, output_path: str) -> None:
    """Compile content into a CSV file with Excel-compatible UTF-8 BOM."""
    matrix = parse_text_to_matrix(content)
    with open(output_path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        for row in matrix:
            writer.writerow(row)


def compile_text(content: str, output_path: str) -> None:
    """Compile plain text or markdown to file."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)


def detect_export_format(prompt: str, input_filename: Optional[str] = None, content: str = "") -> str:
    """
    Determine target export format based on:
    1. Explicit prompt instructions (e.g. 'export as excel', 'convert to word')
    2. Input file extension
    3. Content structure (table-heavy -> xlsx)
    """
    prompt_lower = prompt.lower()

    # 1. Prompt explicit triggers
    if any(k in prompt_lower for k in ["excel", "spreadsheet", ".xlsx", "xlsx", "xls", "workbook"]):
        return "xlsx"
    if any(k in prompt_lower for k in ["word", "docx", ".docx", "word doc", "word document"]):
        return "docx"
    if any(k in prompt_lower for k in ["csv", ".csv"]):
        return "csv"
    if any(k in prompt_lower for k in ["markdown", ".md"]):
        return "md"
    if any(k in prompt_lower for k in ["plain text", "txt file", ".txt"]):
        return "txt"

    # 2. Input file extension match
    if input_filename:
        ext = os.path.splitext(input_filename)[1].lower()
        if ext in [".xlsx", ".xls"]:
            return "xlsx"
        elif ext in [".docx", ".doc"]:
            return "docx"
        elif ext == ".csv":
            return "csv"
        elif ext == ".md":
            return "md"
        elif ext == ".txt":
            return "txt"

    # 3. Content inference
    tables = parse_markdown_tables(content)
    if tables and len(tables[0]) >= 2:
        return "xlsx"

    # Default fallback
    return "docx"


def generate_export_file(
    result_text: str,
    input_filename: Optional[str] = None,
    prompt: str = ""
) -> Dict[str, Any]:
    """
    Generate downloadable file on server and return download metadata.
    """
    downloads_dir = ensure_downloads_dir()
    target_format = detect_export_format(prompt, input_filename, result_text)

    # Build safe base filename and preserve clean human-readable naming
    if input_filename:
        base_name = os.path.splitext(input_filename)[0]
        # Sanitize filename
        base_name = re.sub(r"[^\w\s-]", "", base_name).strip().replace(" ", "_")
        prefix = "transformed"
        lower_prompt = prompt.lower() if prompt else ""
        if "translat" in lower_prompt:
            prefix = "translated"
        elif "summar" in lower_prompt:
            prefix = "summary"
        elif "analy" in lower_prompt:
            prefix = "analysis"
        target_filename = f"{prefix}_{base_name}.{target_format}"
    else:
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        target_filename = f"momento_output_{timestamp}.{target_format}"

    # Strict Filename Integrity: Store directly under clean filename without random hex/uuid prefixes
    file_id = target_filename
    file_path = os.path.join(downloads_dir, file_id)

    title = os.path.splitext(target_filename)[0].replace("_", " ").title()

    # Compile based on format
    if target_format == "docx":
        compile_docx(result_text, file_path, title=title)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    elif target_format == "xlsx":
        compile_xlsx(result_text, file_path, sheet_title="Momento Analysis")
        media_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    elif target_format == "csv":
        compile_csv(result_text, file_path)
        media_type = "text/csv"
    elif target_format == "md":
        compile_text(result_text, file_path)
        media_type = "text/markdown"
    else:
        compile_text(result_text, file_path)
        media_type = "text/plain"

    file_size = os.path.getsize(file_path) if os.path.exists(file_path) else len(result_text.encode("utf-8"))

    return {
        "file_id": file_id,
        "filename": target_filename,
        "format": target_format.upper(),
        "media_type": media_type,
        "size_bytes": file_size,
        "size_human": format_bytes_human(file_size),
        "download_url": f"/api/download/{file_id}",
        "filepath": file_path
    }
